### ISSUE TITLE
Two Column Effect is not working in some page

### ISSUE THREAD

**Issue by happysurf** [wildskyf/two-col-google-search-for-firefox#1]
I think that the version 1.2.0 have problems.
Steps for reproduce:
- Search for example "Pink Floyd" in Google;
- The first page is good, click on second page and still works but if you continue with the third or more the page no more appear in two lines.
Firefox 52.0.2 ESR.

**Comment by wildskyf** [comment]
hi happysurf,

Can you provide your screenshot if you feel ok :)
Or you could just tell me what size is your screen, which might help me to find the bug.

**Comment by happysurf** [comment]
My Asus monitor is 22 " with 1680 x 1050 px resolution.
Sscreenshots:
First page: http://prnt.sc/exu0j5
Second page: http://prnt.sc/exu7rn
Third page: http://prnt.sc/exu85c
Fourth page: http://prntscr.com/exu8xo

**Comment by wildskyf** [comment]
Thank you, @happysurf!
I have submitted the new version to AMO :)
After passed their review, you add-on will get updated.

Thanks a lot for your debugging!!

**Comment by wildskyf** [comment]
@happysurf,

2.0.0 is released, you could try it via reinstall add-on [here](https://addons.mozilla.org/en-US/firefox/addon/2-col-google-results/),or wait for auto-updated.
If the problem is still happened, feel free to reopen this issue. :)

**Comment by happysurf** [comment]
Version 2.0.0 works fine.
Maybe there is still some problems in the first page in case of additional panel info. 
Screenshot: http://prntscr.com/eylyjt
This happen in my notebook 1366x768 px.
Thank you very much.

**Comment by wildskyf** [comment]
@happysurf yeah I know, issue #3 is about this bug.
I will fix it today.
Thank you for your report.

If you have any problem or feature suggestion, feel free to open a new issue!

**Comment by happysurf** [comment]
Sorry but still the images in first page are not aligned to the left:
Screenshot: http://prntscr.com/ez00wy

**Comment by wildskyf** [comment]
@happysurf oh.. I misunderstood.
The problem I described yesterday is about the right side float addition info, which is fixed.
So the problem you found is last area is not align with other normal results, right?

I would find the problem later, please wait for me.
And the issue #4 is for this problem.
