### ISSUE TITLE
Is it possible to expand this addon (or like this addon) to any site?

### ISSUE THREAD

**Issue by difabor** [wildskyf/two-col-google-search-for-firefox#11]
I installed this addon and fully satisfied.
Is it possible that user will be able to expand the power of this addon on any site by clicking some button?
Wide screens aren't so comfortable for eyes and why not to give to user the ability to switch to 2 columns for **any** site that he wants?
If some particular 2-columns layout will not be applicable for him (or he won't like it) he will be able to return to original layout like now.
I tried to do this with this addon, but manifest.json does not allow changes...
By the way, I changed the layout to 3 columns in two-col.css - works excellent.
But only for google...
P.S. Actually it isn't an issue, even opposite, but I don't know where can I ask about such thinks.
Thank you

**Comment by wildskyf** [comment]
Thanks for your suggestion. But I think it is impossible to do this feature. I should know struct of each site so that I could apply two column effect to it.
