### ISSUE TITLE
Distorted results on Google Images

### ISSUE THREAD

**Issue by happysurf** [wildskyf/two-col-google-search-for-firefox#5]
The extension interfere with Google Images.
Steps to reproduce:
- Find on Google "Emma Watson" and click on first vertical portrait photo;
The image appear distorted and fit the area.
- If you disable the extension automatically the image back to the normal size.

**Comment by wildskyf** [comment]
Poor Emma Watson... 

![2017-04-27 20 16 41](https://cloud.githubusercontent.com/assets/6042803/25482950/725a4c6a-2b86-11e7-9f04-8dcb8e0c80f0.png)

Thanks for reporting! I'll fix it when I have time.

**Comment by happysurf** [comment]
Thank you for fix the problem in version 2.1.0.
Just a question, why in gmail page is present in location bar the double "g"icon of extension?

![gg](https://cloud.githubusercontent.com/assets/13637587/26142397/9e3d2eba-3ae0-11e7-8b42-9cf56d0a5e59.png)
Thanks.

**Comment by wildskyf** [comment]
Hi @happysurf ,
I have opened issue #6 for that problem, and it will be fixed in the next version. :)
