### ISSUE TITLE
Not working on other search engines

### ISSUE THREAD

**Issue by noah-be** [wildskyf/two-col-google-search-for-firefox#7]
Hello, I really like your plugin but I dont use the google search engine but a engine called startpage.com. Could you make your plugin work on this page please?
Thanks a lot!

**Comment by wildskyf** [comment]
Hi @ichUndSo2014 

You will find it work on startpage.com after v2.3.0.
Feel free to rise any other features. Thank you. :)

**Comment by noah-be** [comment]
Thank you a lot cant wait for the update :)

**Comment by wildskyf** [comment]
@ichUndSo2014,
I just checked. it works now. Let's close this issue. :)
Feel free to open another issue!

**Comment by noah-be** [comment]
Thank you! I am a bit late ;)
